
OBJS = platformed.cpp

CC = g++

# https://software.intel.com/en-us/blogs/2012/09/26/gcc-x86-performance-hints

# -Wl,-subsystem,windows gets rid of the console window
# -std=c++11 -s -O3 -fno-exceptions -msse3 -fexceptions
# -Ofast -march=native
# -ffast-math
# COMPILER_FLAGS = -Wall -Werror -std=c++11 -s -m64 -mfpmath=sse -Ofast -flto -march=native -funroll-loops
COMPILER_FLAGS = -Wall -Werror -std=c++11

LINKER_FLAGS = -lSDL2 -lGL -lGLEW

OBJ_NAME = app

all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

